version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
       - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres-data:
