version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
       - "postgres-data:/var/lib/postgresql/data"
#    ports:
#      - "5432:5432"

  renderer:
    image: tangelo-renderer
    volumes:
       - "./configuration.json:/app/configuration.json"
    ports:
      - "8080:8080"

volumes:
  postgres-data:
